---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: apache-filebeat-config
  labels:
    app: filebeat
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
     - type: log
       path:
         - /var/log/apache2/*.log
    output.logstash:
      hosts: ["logstash.default.svc.cluster.local:5044"]
---
apiVersion: v1
kind: List
items:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: apache-deployment
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: "apache"
    replicas: 1
    template:
      metadata:
        labels:
          app.kubernetes.io/name: apache
      spec:
        containers:
        - name: apache
          image: ydbalaji/apache-php-fpm:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-log
              mountPath: /var/log/apache2/
        # - name: beat-manual
        #   image: docker.elastic.co/beats/filebeat:7.4.1
        #   args: [
        #     "-c", "/etc/filebeat.yml",
        #     "-e",
        #     "-d", "*",
        #   ]
        #   # command: ["/bin/bash", "-c", "chmod go-w /etc/filebeat.yml"]
        #   volumeMounts:
        #   - name: config
        #     mountPath: /etc/filebeat.yml
        #     readOnly: true
        #     subPath: filebeat.yml
        #   - name: beats-log
        #     mountPath: /tmp/
        volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: apache-filebeat-config
        - name: app-log
          emptyDir: {}
        # - name: beats-log
        #   emptyDir: {}
# ========================================================================
- kind: Service
  apiVersion: v1
  metadata:
    name: apache
    labels:
      app: apache 
  spec:
    type: LoadBalancer
    selector:
      app.kubernetes.io/name: "apache"
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 80 
