apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.5.2
        command: [ "/bin/bash", "-c", "/usr/share/kibana/bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker" ]
        env:
        - name: CLUSTER_NAME
          value: "elasticsearch"
        - name: ELASTIC_SEARCH_URL
          value: "http://elasticsearch.default.svc.cluster.local:9200"
        # - name: ELASTICSEARCH_USERNAME
        #   value: "elastic"
        # - name: ELASTICSEARCH_PASSWORD
        #   value: "changeme"
        # - name: XPACK_MONITORING_ENABLED
        #   value: "false"
        # - name: XPACK_SECURITY_ENABLED
        #   value: "false"
        # - name: XPACK_ML_ENABLED
        #   value: "false"
        # - name: XPACK_GRAPH_ENABLED
        #   value: "false"
        # - name: XPACK_REPORTING_ENABLED
        #   value: "false"
        # - name: XPACK_GROKDEBUGGER_ENABLED
        #   value: "false"
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  # labels:
  #   role: kibana
  name: kibana
spec:
  type: LoadBalancer
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana
    # role: kibana